services:
  base:
    build:
      context: ../../../
      dockerfile: ./dockerfiles/base/Dockerfile
    image: linas/ubbase       # <--- IMPORTANTE: Este nombre lo usarÃ¡n las siguientes capas
    container_name: ctLinasBase
    networks:
      - netlinas

networks:
  netlinas:
    name: netlinas
    driver: bridge